language: android
# See to: https://docs.travis-ci.com/user/languages/android/#installing-a-newer-sdk-platform-tools-revision
android:
  components:
    - tools
    - platform-tools
    # Note that the tools section appears twice on purpose as it’s required to get the newest Android SDK tools.
    - tools
    - build-tools-28.0.3
    - android-28
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

script:
  - ./gradlew build
